### ISSUE TITLE
Reset/Delete all EE Data and Tables

### ISSUE THREAD

**Issue by garthkoyle** [nerrad/wp-cli-event-espresso#13]
There is a feature that allows you to delete all EE data and tables. A command to perform that function might be a tad faster than using the UI. In the UI : Event Espresso > Maintenance > Reset/Delete Data.

**Comment by nerrad** [comment]
So I imagine it would be preferable to have some options with this command:

- delete and remove all traces of EE and deactivate the plugin.
- reset all ee tables (and ee data) to a fresh activation data set and leave the plugin active.
- reset all EE data except EE configuration settings.

**Comment by nerrad** [comment]
So here's what is done, needs done:

* [x] Add reset full: deletes table, all EE data, deactivates plugin.
* [x] Add reset fresh: deletes all EE data and restores to "fresh activation" state.
* [x] Add reset reservations: Resets all ticket and datetime registration counts to 0;
* [x] Add reset caps: Resets EE capabilities to defaults.
* [x] Add documentation for the above.
